# Generated by Django 5.1.6 on 2025-04-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='retrospective',
            name='voted_users',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
