# Generated by Django 5.1.6 on 2025-05-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('task', 'Task'), ('feature', 'Feature')], default='bug', max_length=20),
        ),
    ]
