# Generated by Django 5.1.6 on 2025-07-11 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_bug_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sprint',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_sprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='bug',
            name='type',
            field=models.CharField(choices=[('bug', 'Bug'), ('task', 'Task'), ('feature', 'Feature'), ('wallet', 'Wallet'), ('warning', 'Warning')], default='bug', max_length=20),
        ),
    ]
