# Generated by Django 5.1.6 on 2025-07-15 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sprint_description_sprint_goal_sprint_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sprint',
            name='owner',
        ),
        migrations.AddField(
            model_name='sprint',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sprints_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sprint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sprints', to=settings.AUTH_USER_MODEL),
        ),
    ]
