# Generated by Django 5.1.6 on 2025-07-15 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_sprint_created_at_remove_sprint_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
