# Generated by Django 5.2 on 2025-11-05 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_email', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useremailaccount',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='useremailaccount',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='useremailaccount',
            name='token_expiry',
        ),
    ]
